app/chat/forms.py
from flask import request, g
from flask_login import current_user
from flask_wtf import FlaskForm
from wtforms import StringField, SubmitField, TextAreaField, BooleanField, HiddenField, SelectField, FileField
from wtforms.validators import ValidationError, DataRequired, Email, EqualTo, Length, Optional
from flask_babel import _, lazy_gettext as _l

from app import db
from app.utils import MultiCheckboxField


class AddReply(FlaskForm):
    message = TextAreaField(_l('Message'), validators=[DataRequired(), Length(min=1, max=5000)], render_kw={'placeholder': 'Type a reply here...'})
    submit = SubmitField(_l('Reply'))


class ReportConversationForm(FlaskForm):
    reason_choices = [('7', _l('Spam')),
                      ('2', _l('Harassment')),
                      ('3', _l('Threatening violence')),
                      ('4', _l('Promoting hate / genocide')),
                      ('15', _l('Misinformation / disinformation')),
                      ('16', _l('Racism, sexism, transphobia')),
                      ('5', _l('Minor abuse or sexualization')),
                      ('8', _l('Non-consensual intimate media')),
                      ('9', _l('Prohibited transaction')), ('10', _l('Impersonation')),
                      ('11', _l('Copyright violation')), ('12', _l('Trademark violation')),
                      ('13', _l('Self-harm or suicide')),
                      ('14', _l('Other'))]
    reasons = MultiCheckboxField(_l('Reason'), choices=reason_choices)
    description = StringField(_l('More info'))
    report_remote = BooleanField('Also send report to originating instance')
    submit = SubmitField(_l('Report'))

    def reasons_to_string(self, reason_data) -> str:
        result = []
        for reason_id in reason_data:
            for choice in self.reason_choices:
                if choice[0] == reason_id:
                    result.append(str(choice[1]))
        return ', '.join(result)

app/chat/__init__.py
from flask import Blueprint

bp = Blueprint('chat', __name__)

from app.chat import routes

app/chat/routes.py
from flask import request, flash, json, url_for, current_app, redirect, g, abort
from flask_login import login_required, current_user
from flask_babel import _
from sqlalchemy import desc, or_, and_, text

from app import db, celery
from app.chat.forms import AddReply, ReportConversationForm
from app.chat.util import send_message
from app.models import Site, User, Report, ChatMessage, Notification, InstanceBlock, Conversation, conversation_member, CommunityBan, ModLog
from app.user.forms import ReportUserForm
from app.utils import render_template, moderating_communities, joined_communities, menu_topics, menu_instance_feeds, menu_my_feeds, \
    menu_subscribed_feeds
from app.chat import bp


@bp.route('/chat', methods=['GET', 'POST'])
@bp.route('/chat/<int:conversation_id>', methods=['GET', 'POST'])
@login_required
def chat_home(conversation_id=None):
    form = AddReply()
    if form.validate_on_submit():
        reply = send_message(form.message.data, conversation_id)
        return redirect(url_for('chat.chat_home', conversation_id=conversation_id, _anchor=f'message_{reply.id}'))
    else:
        conversations = Conversation.query.join(conversation_member,
                                                conversation_member.c.conversation_id == Conversation.id). \
            filter(conversation_member.c.user_id == current_user.id).order_by(desc(Conversation.updated_at)).limit(50).all()
        if conversation_id is None:
            if conversations:
                return redirect(url_for('chat.chat_home', conversation_id=conversations[0].id))
            else:
                return redirect(url_for('chat.empty'))
        else:
            conversation = Conversation.query.get_or_404(conversation_id)
            conversation.read = True
            if not current_user.is_admin() and not conversation.is_member(current_user):
                abort(400)
            if conversations:
                messages = conversation.messages.order_by(ChatMessage.created_at).all()
                for message in messages:
                    if message.recipient_id == current_user.id:
                        message.read = True
            else:
                messages = []

            sql = f"UPDATE notification SET read = true WHERE url LIKE '/chat/{conversation_id}%' AND user_id = {current_user.id}"
            db.session.execute(text(sql))
            db.session.commit()
            current_user.unread_notifications = Notification.query.filter_by(user_id=current_user.id, read=False).count()
            db.session.commit()

            return render_template('chat/conversation.html',
                                   title=_('Chat with %(name)s', name=conversation.member_names(current_user.id)),
                                   conversations=conversations, messages=messages, form=form,
                                   current_conversation=conversation_id, conversation=conversation,
                                   moderating_communities=moderating_communities(current_user.get_id()),
                                   joined_communities=joined_communities(current_user.get_id()),
                                   menu_topics=menu_topics(),
                                   site=g.site, menu_instance_feeds=menu_instance_feeds(), 
                                   menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                                   menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                                   )


@bp.route('/chat/<int:to>/new', methods=['GET', 'POST'])
@login_required
def new_message(to):
    recipient = User.query.get_or_404(to)
    if current_user.created_recently() or current_user.reputation <= -10 or current_user.banned or not current_user.verified:
        return redirect(url_for('chat.denied'))
    if recipient.has_blocked_user(current_user.id) or current_user.has_blocked_user(recipient.id):
        return redirect(url_for('chat.blocked'))
    existing_conversation = Conversation.find_existing_conversation(recipient=recipient, sender=current_user)
    if existing_conversation:
        return redirect(url_for('chat.chat_home', conversation_id=existing_conversation.id, _anchor='message'))
    form = AddReply()
    form.submit.label.text = _('Send')
    if form.validate_on_submit():
        conversation = Conversation(user_id=current_user.id)
        conversation.members.append(recipient)
        conversation.members.append(current_user)
        db.session.add(conversation)
        db.session.commit()
        reply = send_message(form.message.data, conversation.id)
        return redirect(url_for('chat.chat_home', conversation_id=conversation.id, _anchor=f'message_{reply.id}'))
    else:
        return render_template('chat/new_message.html', form=form, title=_('New message to "%(recipient_name)s"', recipient_name=recipient.link()),
                               recipient=recipient,
                               moderating_communities=moderating_communities(current_user.get_id()),
                               joined_communities=joined_communities(current_user.get_id()),
                               menu_topics=menu_topics(),
                               site=g.site, menu_instance_feeds=menu_instance_feeds(), 
                               menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                               menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                               )


@bp.route('/chat/denied', methods=['GET'])
@login_required
def denied():
    return render_template('chat/denied.html')


@bp.route('/chat/blocked', methods=['GET'])
@login_required
def blocked():
    return render_template('chat/blocked.html')


@bp.route('/chat/empty', methods=['GET'])
@login_required
def empty():
    return render_template('chat/empty.html')


@bp.route('/chat/ban_from_mod/<int:user_id>/<int:community_id>', methods=['GET'])
@login_required
def ban_from_mod(user_id, community_id):
    active_ban = CommunityBan.query.filter_by(user_id=user_id, community_id=community_id).order_by(desc(CommunityBan.created_at)).first()
    user_link = 'u/' + current_user.user_name
    past_bans = ModLog.query.filter(ModLog.community_id == community_id, ModLog.link == user_link, or_(ModLog.action == 'ban_user', ModLog.action == 'unban_user')).order_by(desc(ModLog.created_at))
    if active_ban:
        past_bans = past_bans.offset(1)
    #if active_ban and len(past_bans) > 1:
    #past_bans = past_bans
    return render_template('chat/ban_from_mod.html', active_ban=active_ban, past_bans=past_bans)


@bp.route('/chat/<int:conversation_id>/options', methods=['GET', 'POST'])
@login_required
def chat_options(conversation_id):
    conversation = Conversation.query.get_or_404(conversation_id)
    if current_user.is_admin() or conversation.is_member(current_user):
        return render_template('chat/chat_options.html', conversation=conversation,
                           moderating_communities=moderating_communities(current_user.get_id()),
                           joined_communities=joined_communities(current_user.get_id()),
                           menu_topics=menu_topics(),
                           site=g.site, menu_instance_feeds=menu_instance_feeds(), 
                           menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                           menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                           )


@bp.route('/chat/<int:conversation_id>/delete', methods=['GET', 'POST'])
@login_required
def chat_delete(conversation_id):
    conversation = Conversation.query.get_or_404(conversation_id)
    if current_user.is_admin() or current_user.is_member(current_user):
        Report.query.filter(Report.suspect_conversation_id == conversation.id).delete()
        db.session.delete(conversation)
        db.session.commit()
        flash(_('Conversation deleted'))
    return redirect(url_for('chat.chat_home'))


@bp.route('/chat/<int:instance_id>/block_instance', methods=['GET', 'POST'])
@login_required
def block_instance(instance_id):
    existing = InstanceBlock.query.filter_by(user_id=current_user.id, instance_id=instance_id).first()
    if not existing:
        db.session.add(InstanceBlock(user_id=current_user.id, instance_id=instance_id))
        db.session.commit()
    flash(_('Instance blocked.'))
    return redirect(url_for('chat.chat_home'))


@bp.route('/chat/<int:conversation_id>/report', methods=['GET', 'POST'])
@login_required
def chat_report(conversation_id):
    conversation = Conversation.query.get_or_404(conversation_id)
    if current_user.is_admin() or conversation.is_member(current_user):
        form = ReportConversationForm()

        if form.validate_on_submit():
            report = Report(reasons=form.reasons_to_string(form.reasons.data), description=form.description.data,
                            type=4, reporter_id=current_user.id, suspect_conversation_id=conversation_id, source_instance_id=1)
            db.session.add(report)

            # Notify site admin
            already_notified = set()
            for admin in Site.admins():
                if admin.id not in already_notified:
                    notify = Notification(title='Reported conversation with user', url='/admin/reports', user_id=admin.id,
                                          author_id=current_user.id)
                    db.session.add(notify)
                    admin.unread_notifications += 1
            db.session.commit()

            # todo: federate report to originating instance
            if form.report_remote.data:
                ...

            flash(_('This conversation has been reported, thank you!'))

app/templates/chat/ban_from_mod.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% set active_child = 'chats' %}

{% block app_content %}
<div class="row">
{% if active_ban %}
  <h5> Active Ban</h5> 
  <table class="table">
    <tr>
      <th>Reason</th>
      <th>From</th>
      <th>Until</th>
    </tr>
    <tr>
      <td>{{ active_ban.reason }}</td>
      <td>{{ active_ban.created_at.strftime('%Y-%m-%d') }}</td>
      <td>{{ active_ban.ban_until.strftime('%Y-%m-%d') if active_ban.ban_until else '' }}</td>
  </table>
{% endif %}
{% if past_bans.count() > 0 %}
  <h5> Ban History</h5>
  <table class="table">
    <tr>
      <th>Reason</th>
      <th>From</th>
      <th>Type</th>
    </tr>
    {% for past_ban in past_bans %}
    <tr>
      <td>{{ past_ban.reason }}</td>
      <td>{{ past_ban.created_at.strftime('%Y-%m-%d') }}</td>
      <td>{{ past_ban.action }}</td>
    </tr>
    {% endfor %}
  </table>
{% endif %}
</div>
{% endblock %}

app/templates/chat/blocked.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% set active_child = 'chats' %}

{% block app_content %}
<div class="row">
        <div class="col col-login mx-auto">
            <div class="card mt-5">
                <div class="card-body p-6">
                    <div class="card-title">{{ _('Sorry') }}</div>
                    <div class="card-body">
                        <p>{{ _('You have blocked this person or they have blocked you.') }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/chat/chat_options.html
<li><a href="{{ url_for('chat.chat_delete', conversation_id=conversation.id) }}" class="dropdown-item no-underline confirm_first" rel="nofollow"><span class="fe fe-delete"></span>
    {{ _('Delete conversation') }}</a></li>
{% for member in conversation.members %}
    {% if member.id != current_user.id %}
        <li><a href="{{ url_for('user.block_profile', actor=member.link()) }}" class="dropdown-item no-underline text-wrap"><span class="fe fe-block"></span>
            {{ _('Block @%(author_name)s', author_name=member.display_name()) }}</a></li>
    {% endif %}
{% endfor %}
{% for instance in conversation.instances() %}
    <li><a href="{{ url_for('chat.block_instance', instance_id=instance.id) }}" class="dropdown-item no-underline text-wrap"><span class="fe fe-block"></span>
        {{ _("Block chats and posts from instance: %(name)s", name=instance.domain) }}</a></li>
{% endfor %}
<li><a href="{{ url_for('chat.chat_report', conversation_id=conversation.id) }}" class="dropdown-item no-underline text-wrap" rel="nofollow"><span class="fe fe-report"></span>
        {{ _('Report to moderators') }}</a></li>
<p class="p-2" style="max-width: 200px;">{{ _('If you are reporting abuse then do not delete the conversation - moderators will not be able to read it if you delete it.') }}</p>

app/templates/chat/conversation.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% set active_child = 'chats' %}
{% from 'bootstrap/form.html' import render_form %}

{% macro conversation_members(conversation) %}
    {% if len(conversation.members) == 2 %}
        {% for member in conversation.members %}
            {% if member.id != current_user.id %}
                <img src="{{ member.avatar_thumbnail() }}" loading="lazy" />
                {% if not conversation.read %}<strong>{% endif %}
                    {{ member.display_name() }}
                {% if not conversation.read %}</strong>{% endif %}
            {% endif %}
        {% endfor %}
    {% else %}
        {% for member in conversation.members %}
            {% if member.id != current_user.id %}
                {% if not conversation.read %}<strong>{% endif %}
                    {{ member.display_name() }}
                {% if not conversation.read %}</strong>{% endif %}
            {% endif %}
        {% endfor %}
    {% endif %}
{% endmacro %}

{% block app_content %}
<div class="row">
    <div class="row">
        <main class="col main_pane">
            <nav aria-label="breadcrumb" id="breadcrumb_nav" title="Navigation">
              <ol class="breadcrumb">
                <li class="breadcrumb-item"><a href="/">{{ _('Home') }}</a></li>
                <li class="breadcrumb-item active">{{ _('Chat') }}</li>
              </ol>
            </nav>
            <div class="row mt-3">
                <div class="col col-md-2 d-none d-md-block sender_list">
                    <h3>{{ _('People') }}</h3>
                    <ul class="list-group list-group-flush">
                    {% for conversation in conversations %}
                        <li class="list-group-item">
                            {% if conversation.id == current_conversation %}
                                {{ conversation_members(conversation) }}
                            {% else %}
                                <a href="{{ url_for('chat.chat_home', conversation_id=conversation.id) }}">
                                    {{ conversation_members(conversation) }}
                                </a>
                            {% endif %}
                        </li>
                    {% endfor %}
                    </ul>
                </div>
                <div class="col col-md-10">
                    {% if messages %}
                        <h3 class="d-none d-md-inline">{{ _('Messages with %(name)s', name=conversation.member_names(current_user.id)) }}</h3>
                        <h3 class="d-md-none">{{ _('Messages with: ') }}
                            <select id="changeSender">{% for conversation in conversations %}
                                        <option value="{{ conversation.id }}" {{ 'selected' if conversation.id == current_conversation }}>{{ conversation.member_names(current_user.id) }}</option>
                                    {% endfor %}
                            </select></h3>
                        <div class="conversation mt-3">
                            {% for message in messages %}
                                <div id="message_{{ message.id }}" class="card message {{ 'from_other_party' if message.sender_id != current_user.id else 'from_me' }}">
                                    <div class="message_body">
                                        <span class="message_created_at text-muted small">{{ arrow.get(message.created_at).humanize(locale=locale) }}</span>
                                        <span class="message_sender"><a href="/u/{{ message.sender.link() }}">{{ message.sender.display_name() }}</a></span>: {{ message.body_html|safe }}
                                    </div>
                                </div>
                            {% endfor %}
                            {{ render_form(form) }}
                            <div class="dropdown">
                                <a 
                                    class="conversation_options btn btn-outline-secondary" 
                                    data-bs-toggle="dropdown" rel="nofollow noindex" 
                                    href="{{ url_for('chat.chat_options', conversation_id=current_conversation) }}" 
                                    class="btn btn-outline-secondary">
                                    {{ _('Options') }}
                                </a>
                                <ul class="dropdown-menu" style="max-width: 240px">
                                    <div 
                                        hx-get="{{ url_for('chat.chat_options', conversation_id=current_conversation) }}"
                                        hx-trigger="intersect once"
                                        hx-target="this"
                                        hx-swap="outerHTML"
                                    ></div>
                                </ul>
                            </div>
                        </div>
                    {% endif %}
                </div>
            </div>
        </main>
    </div>
</div>
{% endblock %}

app/templates/chat/denied.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% from 'bootstrap/form.html' import render_form %}
{% set active_child = 'chats' %}

{% block app_content %}
<div class="row">
        <div class="col col-login mx-auto">
            <div class="card mt-5">
                <div class="card-body p-6">
                    <div class="card-title">{{ _('Sorry') }}</div>
                    <div class="card-body">
                        <p>{{ _('You have not been using PieFed long enough to be allowed to send messages to people.') }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/chat/empty.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% set active_child = 'chats' %}

{% block app_content %}
<div class="row">
        <div class="col col-login mx-auto">
            <div class="card mt-5">
                <div class="card-body p-6">
                    <div class="card-title">{{ _('No chats') }}</div>
                    <div class="card-body">
                        <p>{{ _("There are no chats involving you, yet. Start a conversation using the \"Send message\" button on someone's profile.") }}</p>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/chat/new_message.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% set active_child = 'chats' %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
<div class="row">
        <div class="col col-login mx-auto">
            <div class="card mt-5">
                <div class="card-body p-6">
                    <div class="card-title">{{ _('New message to "%(recipient_name)s"', recipient_name=recipient.link()) }}</div>
                    <div class="card-body">
                        {{ render_form(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

app/templates/chat/report.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% set active_child = 'chats' %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
    <div class="row">
        <div class="col col-login mx-auto">
            <div class="card mt-5">
                <div class="card-body p-6">
                    <div class="card-title">{{ _('Report conversation with "%(member_names)s"', member_names=conversation.member_names(current_user.id)) }}</div>
                    <div class="card-body">
                        {{ render_form(form) }}
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}