app/post/forms.py
from flask_wtf import FlaskForm
from wtforms import TextAreaField, SubmitField, BooleanField, StringField
from wtforms.fields.choices import SelectField
from wtforms.validators import DataRequired, Length, ValidationError
from flask_babel import _, lazy_gettext as _l

from app.utils import MultiCheckboxField


class NewReplyForm(FlaskForm):
    body = TextAreaField(_l('Body'), render_kw={'placeholder': 'What are your thoughts?', 'rows': 5}, validators=[DataRequired(), Length(min=1, max=5000)])
    notify_author = BooleanField(_l('Notify about replies'))
    language_id = SelectField(_l('Language'), validators=[DataRequired()], coerce=int, render_kw={'class': 'form-select language-float-right'})
    submit = SubmitField(_l('Comment'))


class ReportPostForm(FlaskForm):
    reason_choices = [('1', _l('Breaks community rules')), ('7', _l('Spam')), ('2', _l('Harassment')),
                      ('3', _l('Threatening violence')), ('4', _l('Hate / genocide')),
                      ('15', _l('Misinformation / disinformation')),
                      ('16', _l('Racism, sexism, transphobia')),
                      ('6', _l('Sharing personal info - doxing')),
                      ('5', _l('Minor abuse or sexualization')),
                      ('8', _l('Non-consensual intimate media')),
                      ('9', _l('Prohibited transaction')), ('10', _l('Impersonation')),
                      ('11', _l('Copyright violation')), ('12', _l('Trademark violation')),
                      ('13', _l('Self-harm or suicide')),
                      ('14', _l('Other'))]
    reasons = MultiCheckboxField(_l('Reason'), choices=reason_choices)
    description = StringField(_l('More info'))
    report_remote = BooleanField('Also send report to originating instance')
    submit = SubmitField(_l('Report'))

    def reasons_to_string(self, reason_data) -> str:
        result = []
        for reason_id in reason_data:
            for choice in self.reason_choices:
                if choice[0] == reason_id:
                    result.append(str(choice[1]))
        return ', '.join(result)


class MeaCulpaForm(FlaskForm):
    submit = SubmitField(_l('I changed my mind'))


class CrossPostForm(FlaskForm):
    which_community = SelectField(_l('Community to post this link to'), validators=[DataRequired()], coerce=int, render_kw={'class': 'form-select'})
    submit = SubmitField(_l('Next'))

app/instance/__init__.py
from flask import Blueprint

bp = Blueprint('instance', __name__)

from app.instance import routes

app/instance/routes.py
from collections import namedtuple

from flask import request, url_for, g, abort, flash, redirect
from flask_login import current_user, login_required
from flask_babel import _
from sqlalchemy import or_, desc

from app import db, cache
from app.instance import bp
from app.models import Instance, User, Post, read_posts, InstanceBlock
from app.utils import render_template, moderating_communities, joined_communities, menu_topics, blocked_domains, \
    blocked_instances, blocked_communities, blocked_users, user_filters_home, recently_upvoted_posts, \
    recently_downvoted_posts, menu_instance_feeds, menu_my_feeds, menu_subscribed_feeds


@bp.route('/instances', methods=['GET'])
def list_instances():
    page = request.args.get('page', 1, type=int)
    search = request.args.get('search', '')
    filter = request.args.get('filter', '')
    low_bandwidth = request.cookies.get('low_bandwidth', '0') == '1'

    instances = Instance.query.order_by(Instance.domain)
    if search:
        instances = instances.filter(Instance.domain.ilike(f"%{search}%"))
    title = _('Instances')
    if filter:
        if filter == 'trusted':
            instances = instances.filter(Instance.trusted == True)
            title = _('Trusted instances')
        elif filter == 'online':
            instances = instances.filter(Instance.dormant == False, Instance.gone_forever == False)
            title = _('Online instances')
        elif filter == 'dormant':
            instances = instances.filter(Instance.dormant == True, Instance.gone_forever == False)
            title = _('Dormant instances')
        elif filter == 'gone_forever':
            instances = instances.filter(Instance.gone_forever == True)
            title = _('Gone forever instances')

    # Pagination
    instances = instances.paginate(page=page,
                                   per_page=250 if current_user.is_authenticated and not low_bandwidth else 50,
                                   error_out=False)
    next_url = url_for('instance.list_instances', page=instances.next_num) if instances.has_next else None
    prev_url = url_for('instance.list_instances', page=instances.prev_num) if instances.has_prev and page != 1 else None

    return render_template('instance/list_instances.html', instances=instances,
                           title=title, search=search, filter=filter,
                           next_url=next_url, prev_url=prev_url,
                           low_bandwidth=low_bandwidth,
                           moderating_communities=moderating_communities(current_user.get_id()),
                           joined_communities=joined_communities(current_user.get_id()),
                           menu_topics=menu_topics(), site=g.site, menu_instance_feeds=menu_instance_feeds(), 
                           menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                           menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                           )


@bp.route('/instance/<instance_domain>', methods=['GET'])
def instance_overview(instance_domain):
    low_bandwidth = request.cookies.get('low_bandwidth', '0') == '1'

    instance = Instance.query.filter(Instance.domain == instance_domain).first()
    if instance is None:
        abort(404)

    return render_template('instance/overview.html', instance=instance,
                           moderating_communities=moderating_communities(current_user.get_id()),
                           joined_communities=joined_communities(current_user.get_id()),
                           menu_topics=menu_topics(), site=g.site,
                           title=_('%(instance)s overview', instance=instance.domain),
                           menu_instance_feeds=menu_instance_feeds(), 
                           menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                           menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                           )


@bp.route('/instance/<instance_domain>/people', methods=['GET'])
def instance_people(instance_domain):
    page = request.args.get('page', 1, type=int)
    search = request.args.get('search', '')
    filter = request.args.get('filter', '')
    low_bandwidth = request.cookies.get('low_bandwidth', '0') == '1'

    instance = Instance.query.filter(Instance.domain == instance_domain).first()
    if instance is None:
        abort(404)

    if current_user.is_authenticated and current_user.is_admin():
        people = User.query.filter_by(instance_id=instance.id, deleted=False, banned=False).order_by(desc(User.last_seen))
    else:
        people = User.query.filter_by(instance_id=instance.id, deleted=False, banned=False, searchable=True).order_by(desc(User.last_seen))

    # Pagination
    people = people.paginate(page=page, per_page=100 if current_user.is_authenticated and not low_bandwidth else 50, error_out=False)
    next_url = url_for('instance.instance_people', page=people.next_num, instance_domain=instance_domain) if people.has_next else None
    prev_url = url_for('instance.instance_people', page=people.prev_num, instance_domain=instance_domain) if people.has_prev and page != 1 else None

    return render_template('instance/people.html', people=people, instance=instance, next_url=next_url, prev_url=prev_url,
                           moderating_communities=moderating_communities(current_user.get_id()),
                           joined_communities=joined_communities(current_user.get_id()),
                           menu_topics=menu_topics(), site=g.site,
                           title=_('People from %(instance)s', instance=instance.domain),
                           menu_instance_feeds=menu_instance_feeds(), 
                           menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                           menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                           )


@bp.route('/instance/<instance_domain>/posts', methods=['GET'])
def instance_posts(instance_domain):
    page = request.args.get('page', 1, type=int)
    low_bandwidth = request.cookies.get('low_bandwidth', '0') == '1'

    instance = Instance.query.filter(Instance.domain == instance_domain).first()
    if instance is None:
        abort(404)

    if current_user.is_anonymous:
        posts = Post.query.filter(Post.instance_id == instance.id, Post.from_bot == False, Post.nsfw == False, Post.nsfl == False, Post.deleted == False)
        content_filters = {}
    else:
        posts = Post.query.filter(Post.instance_id == instance.id, Post.deleted == False)

        if current_user.ignore_bots == 1:
            posts = posts.filter(Post.from_bot == False)
        if current_user.hide_nsfl == 1:
            posts = posts.filter(Post.nsfl == False)
        if current_user.hide_nsfw == 1:
            posts = posts.filter(Post.nsfw == False)
        if current_user.hide_read_posts:
            posts = posts.outerjoin(read_posts, (Post.id == read_posts.c.read_post_id) & (read_posts.c.user_id == current_user.id))
            posts = posts.filter(read_posts.c.read_post_id.is_(None))  # Filter where there is no corresponding read post for the current user

        domains_ids = blocked_domains(current_user.id)
        if domains_ids:
            posts = posts.filter(or_(Post.domain_id.not_in(domains_ids), Post.domain_id == None))
        instance_ids = blocked_instances(current_user.id)
        if instance_ids:
            posts = posts.filter(or_(Post.instance_id.not_in(instance_ids), Post.instance_id == None))
        community_ids = blocked_communities(current_user.id)
        if community_ids:
            posts = posts.filter(Post.community_id.not_in(community_ids))
        # filter blocked users
        blocked_accounts = blocked_users(current_user.id)
        if blocked_accounts:
            posts = posts.filter(Post.user_id.not_in(blocked_accounts))
        content_filters = user_filters_home(current_user.id)

    # Sorting
    posts = posts.order_by(desc(Post.posted_at))

    # Pagination
    posts = posts.paginate(page=page, per_page=100 if current_user.is_authenticated and not low_bandwidth else 50,
                           error_out=False)
    next_url = url_for('instance.instance_posts', page=posts.next_num, instance_domain=instance_domain) if posts.has_next else None
    prev_url = url_for('instance.instance_posts', page=posts.prev_num, instance_domain=instance_domain) if posts.has_prev and page != 1 else None

    # Voting history
    if current_user.is_authenticated:
        recently_upvoted = recently_upvoted_posts(current_user.id)
        recently_downvoted = recently_downvoted_posts(current_user.id)
    else:
        recently_upvoted = []
        recently_downvoted = []

    breadcrumbs = []
    breadcrumb = namedtuple("Breadcrumb", ['text', 'url'])
    breadcrumb.text = _('Home')
    breadcrumb.url = '/'
    breadcrumbs.append(breadcrumb)
    breadcrumb = namedtuple("Breadcrumb", ['text', 'url'])
    breadcrumb.text = _('Instances')
    breadcrumb.url = '/instances'
    breadcrumbs.append(breadcrumb)
    breadcrumb = namedtuple("Breadcrumb", ['text', 'url'])
    breadcrumb.text = instance.domain
    breadcrumb.url = '/instance/' + instance.domain
    breadcrumbs.append(breadcrumb)

    return render_template('instance/posts.html', posts=posts, show_post_community=True, instance=instance,
                           low_bandwidth=low_bandwidth, recently_upvoted=recently_upvoted, breadcrumbs=breadcrumbs,
                           recently_downvoted=recently_downvoted,
                           next_url=next_url, prev_url=prev_url,
                           #rss_feed=f"https://{current_app.config['SERVER_NAME']}/feed",

app/post/__init__.py
from flask import Blueprint

bp = Blueprint('post', __name__)

from app.post import routes

app/templates/instance/list_instances.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
<div class="row">
    <main class="col-12 col-md-8 position-relative main_pane">
        {% if search == '' %}
            <h1>{{ title }}</h1>
        {% else %}
            <h1>{{ title }}</h1>
        {% endif %}
        <form method="get">
            <input type="search" name="search" value="{{ search }}"> <input type="submit" name="submit" value="{{ _('Search') }}">
        </form>
        <a href="{{ url_for('instance.list_instances', filter='online') }}" rel="nofollow noindex">{{ _('Online') }}</a> |
        <a href="{{ url_for('instance.list_instances', filter='dormant') }}" rel="nofollow noindex">{{ _('Dormant') }}</a> |
        <a href="{{ url_for('instance.list_instances', filter='gone_forever') }}" rel="nofollow noindex">{{ _('Gone forever') }}</a> |
        <a href="{{ url_for('instance.list_instances', filter='trusted') }}" rel="nofollow noindex">{{ _('Trusted') }}</a>

        {% if instances -%}
            <div class="table-responsive-sm pt-4">
                <table class="table table-striped">
                    <tr>
                       <th>{{ _('Instance') }}</th>
                       <th>{{ _('More details') }}</th>
                       <th>{{ _('Software') }}</th>
                       <th>{{ _('Version') }}</th>
                       <th>{{ _('Heard from') }}</th>
                       <th>{{ _('Sent to') }}</th>
                       <th>{{ _('Online') }}</th>
                    </tr>
                    {% for instance in instances %}
                        <tr>
                            <td><a href="{{ url_for('instance.instance_overview', instance_domain=instance.domain) }}">{{ instance.domain }}</a></td>
                            <td><a href="{{ url_for('instance.instance_people', instance_domain=instance.domain) }}">{{ _('People') }}</a>
                                <a href="{{ url_for('instance.instance_posts', instance_domain=instance.domain) }}">{{ _('Posts') }}</a>
                            </td>
                            <td>{{ instance.software  }}</td>
                            <td>{{ instance.version if instance.version }}</td>
                            <td>{{ arrow.get(instance.last_seen).humanize(locale=locale) if instance.last_seen }}</td>
                            <td>{{ arrow.get(instance.last_successful_send).humanize(locale=locale) if instance.last_successful_send }}</td>
                            <td>{% if instance.dormant and instance.gone_forever -%}
                                    {{ _('Gone') }}
                                {% elif instance.dormant -%}
                                    {{ _('Dormant') }}
                                {% else -%}
                                    {{ _('Online') }}
                                {% endif -%}
                            </td>
                        </tr>
                    {% endfor %}
                </table>
            </div>
            <nav aria-label="Pagination" class="mt-4" role="navigation">
            {% if prev_url %}
                <a href="{{ prev_url }}" class="btn btn-primary" rel="nofollow">
                    <span aria-hidden="true">&larr;</span> {{ _('Previous page') }}
                </a>
            {% endif %}
            {% if next_url %}
                <a href="{{ next_url }}" class="btn btn-primary" rel="nofollow">
                    {{ _('Next page') }} <span aria-hidden="true">&rarr;</span>
                </a>
            {% endif %}
            </nav>
        {% else -%}
            <p>{{ _('No results to show.') }}</p>
        {% endif %}
    </main>
</div>



{% endblock %}

app/templates/instance/overview.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
<div class="row">
    <main class="col-12 col-md-8 position-relative main_pane">
        <nav aria-label="breadcrumb" id="breadcrumb_nav" title="Navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">{{ _('Home') }}</a></li>
            <li class="breadcrumb-item"><a href="/instances">{{ _('Instances') }}</a></li>
            <li class="breadcrumb-item active">{{ instance.domain }}</li>
          </ol>
        </nav>
        <h1 class="mt-2">{{ _('%(instance)s overview', instance=instance.domain) }}</h1>
        <p>{{ _('This is a %(software)s instance.', software=instance.software) }}</p>
        <p><a href="{{ url_for('instance.instance_people', instance_domain=instance.domain) }}">{{ _('People') }}</a><br />
                                <a href="{{ url_for('instance.instance_posts', instance_domain=instance.domain) }}">{{ _('Posts') }}</a></p>
        <p><a href="https://{{ instance.domain }}" rel="noopener nofollow noindex noreferrer">{{ _('Go to instance') }} <span class="fe fe-external"></span></a></p>
    </main>

    <aside id="side_pane" class="col-12 col-md-4 side_pane" role="complementary">

        <div class="card">
            <div class="card-body">
                {% if current_user.is_authenticated -%}
                    {% if current_user.has_blocked_instance(instance.id) -%}
                        <a class="btn btn-primary" href="{{ url_for('instance.instance_unblock', instance_id=instance.id, redirect='/instance/' + instance.domain) }}" rel="nofollow">{{ _('Unblock %(instance_name)s', instance_name=instance.domain) }}</a>
                    {% else %}
                        <a class="btn btn-primary confirm_first" href="{{ url_for('instance.instance_block', instance_id=instance.id, redirect='/instance/' + instance.domain) }}" rel="nofollow">{{ _('Block everyone from %(instance_name)s', instance_name=instance.domain) }}</a>
                    {% endif -%}
                {% endif -%}
            </div>
        </div>
    </aside>
</div>
{% endblock %}

app/templates/instance/people.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
<div class="row">
    <main class="col-12 col-md-8 position-relative main_pane">
        <nav aria-label="breadcrumb" id="breadcrumb_nav" title="Navigation">
          <ol class="breadcrumb">
            <li class="breadcrumb-item"><a href="/">{{ _('Home') }}</a></li>
            <li class="breadcrumb-item"><a href="/instances">{{ _('Instances') }}</a></li>
            <li class="breadcrumb-item"><a href="/instance/{{ instance.domain }}">{{ instance.domain }}</a></li>
            <li class="breadcrumb-item active">{{ _('People') }}</li>
          </ol>
        </nav>
        <h1 class="mt-2">{{ _('People from %(instance)s', instance=instance.domain) }}</h1>
        {% if people %}
            <table class="table table-striped">
                <tr>
                    <th>{{ _('Name') }}</th>
                    <th>{{ _('About') }}</th>
                    <th>{{ _('Posts') }}</th>
                    <th>{{ _('Comments') }}</th>
                </tr>
                {% for person in people.items %}
                    <tr>
                        <td valign="top">{{ render_username(person) }}</td>
                        <td class="profile_bio">{{ person.about_html | safe if person.about_html }}</td>
                        <td valign="top">{{ person.post_count }}</td>
                        <td valign="top">{{ person.post_reply_count }}</td>
                    </tr>
                {% endfor %}
            </table>
            <nav aria-label="Pagination" class="mt-4" role="navigation">
                {% if prev_url -%}
                    <a href="{{ prev_url }}" class="btn btn-primary" rel='nofollow'>
                        <span aria-hidden="true">&larr;</span> {{ _('Previous page') }}
                    </a>
                {% endif -%}
                {% if next_url -%}
                    <a href="{{ next_url }}" class="btn btn-primary" rel='nofollow'>
                        {{ _('Next page') }} <span aria-hidden="true">&rarr;</span>
                    </a>
                {% endif -%}
            </nav>
        {% else %}
            <p>{{ _('No people to show') }}</p>
        {% endif %}
    </main>

    <aside id="side_pane" class="col-12 col-md-4 side_pane" role="complementary">

        <div class="card">
            <div class="card-header">
                 <h2> </h2>
            </div>
            <div class="card-body">

            </div>
        </div>
    </aside>
</div>
{% endblock %}

app/templates/instance/posts.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') -%}
    {% extends 'themes/' + theme() + '/base.html' -%}
{% else -%}
    {% extends "base.html" -%}
{% endif -%} -%}
{% from 'bootstrap/form.html' import render_form -%}

{% block app_content -%}
<div class="row">
    <main class="col-12 col-md-8 position-relative main_pane">
        <nav aria-label="breadcrumb" id="breadcrumb_nav" title="Navigation">
          <ol class="breadcrumb">
            {% for breadcrumb in breadcrumbs -%}
              <li class="breadcrumb-item">{% if breadcrumb.url -%}<a href="{{ breadcrumb.url }}">{% endif -%}{{ breadcrumb.text }}{% if breadcrumb.url -%}</a>{% endif -%}</li>
            {% endfor -%}
            <li class="breadcrumb-item active">{{ _('Posts') }}</li>
          </ol>
        </nav>
        <h1 class="mt-2">{{ _("Posts from %(instance)s", instance=instance.domain) }}</h1>

        <div class="post_list">
            {% for post in posts.items -%}
                {% include 'post/_post_teaser.html' -%}
            {% else -%}
                <p>{{ _('No posts from this instance yet.') }}</p>
            {% endfor -%}
        </div>

        <nav aria-label="Pagination" class="mt-4" role="navigation">
                {% if prev_url -%}
                    <a href="{{ prev_url }}" class="btn btn-primary" rel='nofollow'>
                        <span aria-hidden="true">&larr;</span> {{ _('Previous page') }}
                    </a>
                {% endif -%}
                {% if next_url -%}
                    <a href="{{ next_url }}" class="btn btn-primary" rel='nofollow'>
                        {{ _('Next page') }} <span aria-hidden="true">&rarr;</span>
                    </a>
                {% endif -%}
        </nav>
    </main>

    {% include "_side_pane.html" %}
</div>
<div class="row">


</div>
{% endblock -%}