app/search/__init__.py
from flask import Blueprint

bp = Blueprint('search', __name__)

from app.search import routes

app/search/routes.py
from flask import request, flash, json, url_for, current_app, redirect, g, abort
from flask_login import login_required, current_user
from flask_babel import _
from sqlalchemy import or_, desc

from app import limiter
from app.models import Post, Language, Community, Instance
from app.search import bp
from app.utils import moderating_communities, joined_communities, render_template, blocked_domains, blocked_instances, \
    communities_banned_from, recently_upvoted_posts, recently_downvoted_posts, blocked_users, menu_topics, \
    blocked_communities, show_ban_message, menu_instance_feeds, menu_my_feeds, menu_subscribed_feeds
from app.community.forms import RetrieveRemotePost
from app.activitypub.util import resolve_remote_post_from_search


@bp.route('/search', methods=['GET', 'POST'])
@limiter.limit("100 per day;20 per 5 minutes", exempt_when=lambda: current_user.is_authenticated)
def run_search():
    if 'bingbot' in request.user_agent.string:  # Stop bingbot from running nonsense searches
        abort(404)
    languages = Language.query.order_by(Language.name).all()
    communities = Community.query.filter(Community.banned == False).order_by(Community.name)
    instance_software = Instance.unique_software_names()
    if current_user.is_authenticated:
        banned_from = communities_banned_from(current_user.id)
        communities = communities.filter(Community.id.not_in(banned_from))
    else:
        banned_from = []

    page = request.args.get('page', 1, type=int)
    community_id = request.args.get('community', 0, type=int)
    language_id = request.args.get('language', 0, type=int)
    type = request.args.get('type', 0, type=int)
    software = request.args.get('software', '')
    low_bandwidth = request.cookies.get('low_bandwidth', '0') == '1'
    q = request.args.get('q')
    sort_by = request.args.get('sort_by', '')

    if q is not None or type != 0 or language_id != 0 or community_id != 0:
        posts = Post.query.filter(Post.deleted == False)
        if current_user.is_authenticated:
            if current_user.ignore_bots == 1:
                posts = posts.filter(Post.from_bot == False)
            if current_user.hide_nsfl == 1:
                posts = posts.filter(Post.nsfl == False)
            if current_user.hide_nsfw == 1:
                posts = posts.filter(Post.nsfw == False)
            domains_ids = blocked_domains(current_user.id)
            if domains_ids:
                posts = posts.filter(or_(Post.domain_id.not_in(domains_ids), Post.domain_id == None))
            instance_ids = blocked_instances(current_user.id)
            if instance_ids:
                posts = posts.filter(or_(Post.instance_id.not_in(instance_ids), Post.instance_id == None))
            community_ids = blocked_communities(current_user.id)
            if community_ids:
                posts = posts.filter(Post.community_id.not_in(community_ids))
            # filter blocked users
            blocked_accounts = blocked_users(current_user.id)
            if blocked_accounts:
                posts = posts.filter(Post.user_id.not_in(blocked_accounts))
            if banned_from:
                posts = posts.filter(Post.community_id.not_in(banned_from))
        else:
            posts = posts.filter(Post.from_bot == False)
            posts = posts.filter(Post.nsfl == False)
            posts = posts.filter(Post.nsfw == False)

        posts = posts.filter(Post.indexable == True)
        if q is not None:
            posts = posts.search(q, sort=True if sort_by == '' else False)
        if type != 0:
            posts = posts.filter(Post.type == type)
        if community_id:
            posts = posts.filter(Post.community_id == community_id)
        if language_id:
            posts = posts.filter(Post.language_id == language_id)
        if software:
            posts = posts.join(Instance, Post.instance_id == Instance.id).filter(Instance.software == software)
        if sort_by == 'date':
            posts = posts.order_by(desc(Post.posted_at))
        elif sort_by == 'top':
            posts = posts.order_by(desc(Post.up_votes - Post.down_votes))

        posts = posts.paginate(page=page, per_page=100 if current_user.is_authenticated and not low_bandwidth else 50,
                               error_out=False)

        next_url = url_for('search.run_search', page=posts.next_num, q=q) if posts.has_next else None
        prev_url = url_for('search.run_search', page=posts.prev_num, q=q) if posts.has_prev and page != 1 else None

        # Voting history
        if current_user.is_authenticated:
            recently_upvoted = recently_upvoted_posts(current_user.id)
            recently_downvoted = recently_downvoted_posts(current_user.id)
        else:
            recently_upvoted = []
            recently_downvoted = []

        return render_template('search/results.html', title=_('Search results for %(q)s', q=q), posts=posts, q=q,
                               community_id=community_id, language_id=language_id, communities=communities.all(),
                               languages=languages,
                               next_url=next_url, prev_url=prev_url, show_post_community=True,
                               recently_upvoted=recently_upvoted,
                               recently_downvoted=recently_downvoted,
                               moderating_communities=moderating_communities(current_user.get_id()),
                               joined_communities=joined_communities(current_user.get_id()),
                               menu_topics=menu_topics(),
                               site=g.site, menu_instance_feeds=menu_instance_feeds(), 
                               menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                               menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                               )

    else:
        return render_template('search/start.html', title=_('Search'), communities=communities.all(),
                               languages=languages, instance_software=instance_software,
                               moderating_communities=moderating_communities(current_user.get_id()),
                               joined_communities=joined_communities(current_user.get_id()),
                               menu_topics=menu_topics(),
                               site=g.site, menu_instance_feeds=menu_instance_feeds(), 
                               menu_my_feeds=menu_my_feeds(current_user.id) if current_user.is_authenticated else None,
                               menu_subscribed_feeds=menu_subscribed_feeds(current_user.id) if current_user.is_authenticated else None,
                               )


@bp.route('/retrieve_remote_post', methods=['GET', 'POST'])
@login_required
def retrieve_remote_post():
    if current_user.banned:
        return show_ban_message()
    form = RetrieveRemotePost()
    new_post = None
    if form.validate_on_submit():
        address = form.address.data.strip()
        new_post = resolve_remote_post_from_search(address)
        if new_post is None:
            flash(_('Post not found.'), 'warning')

    return render_template('community/retrieve_remote_post.html',
                           title=_('Retrieve Remote Post'), form=form, new_post=new_post)

app/templates/search/results.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
<div class="row">
    <main class="col-12 col-md-8 position-relative main_pane">
        <h1>{{ _('Search results for') }} <form method="get" class="redo_search"><input type="search" name="q" value="{{ q }}" class="form-control">
        <input type="hidden" name="community" value="{{ community_id }}">
        <input type="hidden" name="language" value="{{ language_id }}">
        </form></h1>
        <div class="post_list">
            {% for post in posts.items %}
                {% include 'post/_post_teaser.html' %}
            {% else %}
                <p>{{ _('No posts match your search.') }}</p>
            {% endfor %}
        </div>

        <nav aria-label="Pagination" class="mt-4" role="navigation">
                {% if prev_url %}
                    <a href="{{ prev_url }}" class="btn btn-primary" rel="nofollow">
                        <span aria-hidden="true">&larr;</span> {{ _('Previous page') }}
                    </a>
                {% endif %}
                {% if next_url %}
                    <a href="{{ next_url }}" class="btn btn-primary" rel="nofollow">
                        {{ _('Next page') }} <span aria-hidden="true">&rarr;</span>
                    </a>
                {% endif %}
        </nav>
    </main>

    <aside id="side_pane" class="col-12 col-md-4 side_pane" role="complementary">
        <!-- <div class="card">
            <div class="card-body">
                <form method="get">
                    <input type="search" name="search" class="form-control mt-2" placeholder="{{ _('Search') }}" />
                </form>
            </div>
        </div> -->

        <div class="card mt-3">
            <div class="card-header">
                 <h2>{{ _('Active communities') }}</h2>
            </div>
            <div class="card-body">
                <ul class="list-group list-group-flush">
                    {% for community in active_communities %}
                        <li class="list-group-item">
                            {{ render_communityname(community) }}
                        </li>
                    {% endfor %}
                </ul>
                <p class="mt-4"><a class="btn btn-primary" href="/communities">{{ _('More communities') }}</a>
                    <a class="btn btn-primary" href="/topics">{{ _('Browse topics') }}</a>
                </p>
            </div>
        </div>

        <div class="card mt-3">
            <div class="card-header">
                 <h2>{{ _('About %(site_name)s', site_name=g.site.name) }}</h2>
            </div>
            <div class="card-body">
                <p><strong>{{ g.site.description|safe }}</strong></p>
                <p>{{ g.site.sidebar|safe }}</p>
                {% if rss_feed %}
                <p class="mt-4">
                    <a class="no-underline" href="{{ rss_feed }}" rel="nofollow"><span class="fe fe-rss"></span> RSS feed</a>
                </p>
                {% endif %}
            </div>
        </div>

        {% include "_inoculation_links.html" %}
    </aside>
</div>
{% endblock %}

app/templates/search/start.html
{% if theme() and file_exists('app/templates/themes/' + theme() + '/base.html') %}
    {% extends 'themes/' + theme() + '/base.html' %}
{% else %}
    {% extends "base.html" %}
{% endif %}
{% from 'bootstrap/form.html' import render_form %}

{% block app_content %}
        <div class="row">
            <div class="col mx-auto">
                <div class="card mt-5" style="width: 500px; max-width: 100%;">
                    <div class="card-body p-6">
                        <div class="card-title">{{ _('Search for posts') }}</div>
                        <form action="" method="get" class="form" role="form">
                            <div class="form-group"><label class="form-control-label" for="search_term" aria-label="Search here">{{ _('Keyword') }} ({{ _('optional') }})</label>
                                <input autofocus="" class="form-control" id="search_term" name="q" type="search" value="">
                            </div>
                            <div class="form-group"><label class="form-control-label" for="community" aria-label="Restrict results by community">{{ _('Community') }}</label>
                                <select class="form-control form-select" id="community" name="community">
                                    <option value="0">{{ _('All') }}</option>
                                    {% for community in communities %}
                                        <option value="{{ community.id }}">{{ community.display_name() }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group"><label class="form-control-label" for="type" aria-label="Restrict results by type">{{ _('Type') }}</label>
                                <select class="form-control form-select" id="type" name="type">
                                    <option value="0">{{ _('All') }}</option>
                                    <option value="{{ POST_TYPE_ARTICLE }}">{{ _('Discussion') }}</option>
                                    <option value="{{ POST_TYPE_LINK }}">{{ _('Link') }}</option>
                                    <option value="{{ POST_TYPE_IMAGE }}">{{ _('Image') }}</option>
                                    <option value="{{ POST_TYPE_VIDEO }}">{{ _('Video') }}</option>
                                    <option value="{{ POST_TYPE_POLL }}">{{ _('Poll') }}</option>
                                </select>
                            </div>
                            <div class="form-group"><label class="form-control-label" for="language" aria-label="Restrict results by language">{{ _('Language') }}</label>
                                <select class="form-control form-select" id="language" name="language">
                                    <option value="0">{{ _('All') }}</option>
                                    {% for language in languages %}
                                        <option value="{{ language.id }}">{{ language.name }}</option>
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group"><label class="form-control-label" for="software" aria-label="Restrict results by instance software">{{ _('Instance Software') }}</label>
                                <select class="form-control form-select" id="software" name="software">
                                    <option value="">{{ _('All') }}</option>
                                    {% for software in instance_software %}
                                        {% if not software =='guppe groups' %}
                                            <option value="{{ software }}">{{ software }}</option>
                                        {% endif %}
                                    {% endfor %}
                                </select>
                            </div>
                            <div class="form-group"><label class="form-control-label" for="type" aria-label="Sort results">{{ _('Sort by') }}</label>
                                <select class="form-control form-select" id="sort_by" name="sort_by">
                                    <option value="">{{ _('Relevance') }}</option>
                                    <option value="date">{{ _('Recent first') }}</option>
                                    <option value="top">{{ _('Top') }}</option>
                                </select>
                            </div>
                            <input class="btn btn-primary btn-md" id="submit" name="submit" type="submit" value="Search">
                        </form>
                        <h6 class="mt-5">{{ _('Example searches:') }} </h6>
                        <table class="table">
                            <tr>
                                <td nowrap="nowrap"><p>{{ _('star wars') }}</p></td>
                                <td><p>{{ _('There is an implied "and" here. Results will have both words somewhere in them.') }}</p></td>
                            </tr>
                            <tr>
                                <td nowrap="nowrap"><p>{{ _('star or wars') }}</p></td>
                                <td><p>{{ _('This will broaden the search to include results that contain any of the words.') }}</p></td>
                            </tr>
                            <tr>
                                <td nowrap="nowrap"><p>{{ _('star -wars') }}</p></td>
                                <td><p>{{ _('To search for things containing "star" but not "wars" you can put a - before the word you want to exclude.') }}</p></td>
                            </tr>
                            <tr>
                                <td nowrap="nowrap"><p>{{ _('"star wars"') }}</p></td>
                                <td><p>{{ _('Results will have exactly that phrase in them.') }}</p></td>
                            </tr>
                        </table>
                        <h6 class="mt-5">{{ _('Trying to add a communitiy or post from another instance?') }} </h6>
                        <p>{{ _('In many types of federated platforms you can put a URL of a post or community into the search in order to add it to your local instance. In PieFed the search is just for searching.') }}</p>
                        <p><a href="{{ url_for('community.add_remote') }}" class="btn btn-primary">{{ _('Add remote community') }}</a></p>
                        <p><a href="{{ url_for('search.retrieve_remote_post') }}" class="btn btn-primary">{{ _('Retrieve remote post') }}</a></p>
                    </div>
                </div>
            </div>
        </div>
{% endblock %}